# Check PRs targeting the release brach to ensure they are from the release GHA workflow.

name: Check release PR

on:
  # push:
  #   branches:
  #     - chore/gha-release-pr-check
  pull_request:
    branches:
      - ameter/test-release-clean  # will change to release after testing

# Limit the GITHUB_TOKEN permissions
permissions: {}

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    #if: ${{ !github.event.issue.pull_request && (contains(github.event.issue.labels.*.name, 'pending-response') || contains(github.event.issue.labels.*.name, 'closing soon')) }}

    steps:
      - name: Check
        shell: bash
        run: |
          echo user: ${{ github.event.comment.user.login }}
          echo GITHUB_ACTOR: $GITHUB_ACTOR
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_REF_NAME: $GITHUB_REF_NAME

      - name: Verify head ref is 'main'
        if: ${{ github.head_ref != 'chore/gha-release-pr-check' }} #chore/gha-release-pr-check' }} # will change to main after testing
        run: |
          echo Invalid Pull Request!
          echo PRs targetting the release branch must have a head ref of main.
          echo Current head ref: $GITHUB_HEAD_REF
          exit 1

      - name: "Verify PR title is 'chore: Kickoff release'" 
      - env:
          TITLE: ${{ github.event.pull_request.title }}
          TEST: 
        run: |
          echo $TITLE
